### ISSUE TITLE
can you Update to vue-sidebar-menu 4.4.0

### ISSUE THREAD

**Issue by slimani-dev** [DashboardPack/architectui-vue-theme-free#1]
the new version of vue-sidebar-menu hase support for pathToRegexp
thank you

**Comment by punyflash** [comment]
vue-sidebar-menu changed component stucture in newer version, so it takes a few time to restyle it properly. You may check my fork If you still need it https://github.com/PunyFlash/architectui-vue

**Comment by DPTeamMember** [comment]
Hello @moh-slimani 

We will include support for vue-sidebar-menu version 4 in the next release with Vue 3.

Thank you.
