### ISSUE TITLE
Side menu doesn't hide

### ISSUE THREAD

**Issue by rahamatj** [DashboardPack/architectui-vue-theme-free#4]
Side menu doesn't hide when the hide button is clicked. And after visiting the login page the side menu stays hidden, only opens on hover and there's no way to keep it always open.

**Comment by DPTeamMember** [comment]
Hello @rahamatj 

We will resolve the issue in the next possible release.

Thank you.

**Comment by TariqAbbas514** [comment]
@rahamatj  How did you run this on a local machine after unzipping?
What steps to follow in?

**Comment by DPTeamMember** [comment]
Hello @TariqAbbas514 

To run the template you just need to run the following two commands on the root directory of the template.
1. npm install
2. npm run serve

Thank you.
