### ISSUE TITLE
URGENT: Login-Boxed page modal doesn't center vertically on screen

### ISSUE THREAD

**Issue by susthitsoft** [DashboardPack/architectui-vue-theme-free#7]
Hi,

Just purchased pro version.
Did npm install and npm run serve ..

1. Checked the /pages/login (LoginBoxed.vue) page.
It doesn't center vertically like in Demos.

2. Also Login page appears to be messed up. 
None of the above pages have height 100% of the view i.e h-100.

3. 
Firefox console shows following warning
This page uses the non standard property “zoom”. Consider using calc() in the relevant property values, or using “transform” along with “transform-origin: 0 0”.

Check ScreenShots
Login Page
![Screenshot 2020-12-18 at 11 17 20 PM](https://user-images.githubusercontent.com/40543676/102644675-36c1e800-4187-11eb-814a-bf6bf6dea1dc.png)

Login Boxed
![Screenshot 2020-12-18 at 11 15 31 PM](https://user-images.githubusercontent.com/40543676/102644626-1c880a00-4187-11eb-99d7-c79699b62aff.png)

**Comment by DPTeamMember** [comment]
Hello @susthitsoft 

We have resolved this issue in our latest release, Please review.

Thank you.
